export interface ActionInterface {
  type: string;
  payload: any;
}

export const ACTIVITY = "ACTIVITY";
export const CATEGORY = "CATEGORY";
export const SUMMARY = "SUMMARY";

export const CREATE_ACTIVITY = "CREATE_ACTIVITY";
export const FETCH_ACTIVITIES = "FETCH_ACTIVITIES";
export const FETCH_ACTIVITY = "FETCH_ACTIVITY";
export const EDIT_ACTIVITY = "EDIT_ACTIVITY";
export const DELETE_ACTIVITY = "DELETE_ACTIVITY";

export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const FETCH_CATEGORY = "FETCH_CATEGORY";
export const EDIT_CATEGORY = "EDIT_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";

export const FETCH_SUMMARIES = "FETCH_SUMMARIES";

// LOADING
export const ACTIVITY_REQUEST = "ACTIVITY_REQUEST";
export const ACTIVITY_COMPLETE = "ACTIVITY_COMPLETE";
export const ACTIVITY_ERROR = "ACTIVITY_ERROR";

export const CATEGORY_REQUEST = "CATEGORY_REQUEST";
export const CATEGORY_COMPLETE = "CATEGORY_COMPLETE";
export const CATEGORY_ERROR = "CATEGORY_ERROR";

export const SUMMARY_REQUEST = "SUMMARY_REQUEST";
export const SUMMARY_COMPLETE = "SUMMARY_COMPLETE";
export const SUMMARY_ERROR = "SUMMARY_ERROR";

// LENDER
export const FETCH_LENDERS = "FETCH_LENDERS";
export const CREATE_LENDER = "CREATE_LENDER";
export const FETCH_LENDER = "FETCH_LENDER";
export const EDIT_LENDER = "EDIT_LENDER";
export const DELETE_LENDER = "DELETE_LENDER";

// TRANSACTION
export const FETCH_TRANSACTIONS = "FETCH_TRANSACTIONS";
export const FETCH_TRANSACTIONS_BY_LENDER = "FETCH_TRANSACTIONS_BY_LENDER";
export const CREATE_TRANSACTION = "CREATE_TRANSACTION";
export const FETCH_TRANSACTION = "FETCH_TRANSACTION";
export const EDIT_TRANSACTION = "EDIT_TRANSACTION";
export const DELETE_TRANSACTION = "DELETE_TRANSACTION";
